---
kind: pipeline
type: kubernetes
name: slon-ui-blueprint-styles

steps:
  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
      token:
        from_secret: npm_token
  
  - name: notify
    image: registry.taxi-beton.ua/drone-telegram:latest
    pull: always
    settings:
      message_file: npm_message
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
    when:
      status: [ success, failure ]
  
  - name: trigger
    image: plugins/downstream
    settings:
      server:
        from_secret: drone_server
      token:
        from_secret: drone_token
      repositories:
        - dmytro-balytskyi/slon-ui-menu24
    when:
      status: [success]

trigger:
  branch:
    - master
  event:
    - push
---
kind: signature
hmac: fc6a95a2bf8aebd78b5ff845d7438a341b5dc04f039d042cbd92ac24ad4a065f

...
